spring:
  application:
    name: demo-ai
  ai:
    openai:
      base-url: https://dashscope.aliyuncs.com/compatible-mode
      api-key: sk-26450bac21234edc8c8b9a40c1581d93
      chat:
        options:
          model: qwen3-max
          temperature: 0.8
logging:
  level:
    org.springframework.ai.chat.client.advisor: debug
    com.example.demoai: debug